### ISSUE TITLE
throw error if configurator isn't running when it should be 

### ISSUE THREAD

**Issue by yochannah** [intermine/intermine_compose#12]
If I forget to run 
`docker run --rm -p 9999:8080 --env IM_DATA_DIR=/intermine/data intermine/configurator:latest`, compose still comfortably launches, the wizard ui allows registration, then throws an error on login that looks like this: [error.txt](https://github.com/intermine/intermine_compose/files/3457505/error.txt)

it would be nice to have a clear error telling us that we've been silly and forgot to start a server! :)

**Comment by leoank** [comment]
login and configurator endpoints are not dependent on each other. Wizard must be calling configurator endpoints after login. But anyway, I have added error handling in configurator routes now. Thanks for the issue!
