### ISSUE TITLE
postgres user 

### ISSUE THREAD

**Issue by sergiocontrino** [intermine/intermine_compose#25]
current setting requires a user postgres with  same password.
it should use a configurable u/p (or at least not postgres?)

**Comment by sergiocontrino** [comment]
possibly configured in config/development.py

**Comment by leoank** [comment]
- create a `.env` file in the root of this repo. 
- Use this file to define `FLASK_CONFIG_MODE` to select a config in the config dir.
  - Some configs for general use cases are already defined.
- If you need full customization of all params then use `production` config mode and define all of the params in the `.env` file like `PGUSER`,  `PGPASSWORD` and `PGHOST`. 
- You can also add these params as env vars and avoid using a `.env` file.

**Comment by sergiocontrino** [comment]
thank you @leoank! i'll add this to the README and close this.

**Comment by sergiocontrino** [comment]
updated readme
