### ISSUE TITLE
POST /data/file should have URL or local file path

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine_compose#6]
`POST /data/file` just looks like it accepts the file contents. (Is that right?)

Instead it should accept the `remoteURL` or the path the upload the file from.

**Comment by julie-sullivan** [comment]
Can we change to be `/data/file/upload` too? Just to be really obvious about what it's doing?

**Comment by leoank** [comment]
- `/data/file` is originally designed to accept file contents. I have to update it with a remoteURL key to support pulling files from cloud storage providers.
 - Sure. `/data/file/upload` is more intuitive.
