### ISSUE TITLE
ISATools end point - no array

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine_compose#7]
1. We'll only have a single JSON file for ISA, not an array
2. It should use the object created to fix #6. e.g. it won't have file contents, instead it will have a URL pointing to the JSON file.

I kept saying it would be a zipped file. It won't! That was the old TAB files. We're only accepting the ISA JSON files.

**Comment by leoank** [comment]
So instead of receiving a JSON file, now we will only receive a  remote URL?
