### ISSUE TITLE
add fileId and userId 

### ISSUE THREAD

**Issue by julie-sullivan** [intermine/intermine_compose#8]
1. some (all?) end points need the `userId`
2. `/data/file/upload` and `/data/file/upload/remote` 
    * do these need to return the fileId? I think so.
    * provide mineId?
3. `/build/trigger` and `/build/status` needs the `mineId`

**Comment by leoank** [comment]
1. clients don't need to send a userId on any request. It will be inferred from the auth token
2. You are right. I will update this.
3. Yes, I will update this too.
