### ISSUE TITLE
JSON didn't merge properly

### ISSUE THREAD

**Issue by intermineorg** [intermine/intermine_compose#9]
The JSON files didn't merge properly. e.g. I removed this end point:

`"/mine/config/delete/{mineId}":`

I don't know if there are more errors. 

If this is a big issue, we can manually update. There won't be many large changes (enough to trick your script anyway!) going forward.

**Comment by leoank** [comment]
merger script is just comparing keys from two json documents. It merges checking 2 conditions:
 - whenever a key exists in both json documents, and both keys are different, then it replaces compose's key with configurator's key.
- if a key exists in configurator json but not in compose json then it adds that key to compose

So if you remove a key from configurator json and that key still exists in compose, then nothing happens.
There are lot of keys in compose that does not exist in the configurator.

I don't think there is an easy way to fix this in merger script. Possible solutions are, maybe compare current configurator config with its previous version and remeber the deleted keys and then while comparing with compose, if those keys exist then delete them from compose as well.

for now, I will manually update the config. I need to update it anyway with few changes.
